name: Merge Markdown Documentation

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  merge-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown

      - name: Run merge script
        run: python merge_docs.py

      - name: Commit and push merged documentation
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add merged-docs.md
          git commit -m "Update merged documentation"
          git push