# Version: 1.3.0 - Added rebase step to handle remote changes before pushing
name: Merge Markdown Documentation

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  merge-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Version 4 - Latest version
        with:
          ref: main # Ensure you're working on the main branch

      - name: Set up Python
        uses: actions/setup-python@v4 # Version 4 - Latest version
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown

      - name: Run merge script
        run: python merge_docs.py

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Pull and Rebase changes
        run: |
          git fetch origin
          git rebase origin/main || exit 0 # Exit gracefully if rebase fails

      - name: Commit and push merged documentation
        run: |
          git add merged-docs.md
          git commit -m "Update merged documentation" || exit 0 # Exit gracefully if no changes to commit
          git push origin main
